# Generated by Django 2.1.1 on 2019-06-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyTable',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
    ]
