# Generated by Django 2.1.1 on 2019-06-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
